### ISSUE TITLE
make backups of db - due oct 14th

### ISSUE THREAD

**Issue by digipam** [DigiVino/HOW-TO-KEEP-SITES-SAFE#1]
[10/7/15, 10:37:45 PM] Andrew Greenberg: the real issue is to appoint SOMEONE with the responsibility to periodically back up and save the files — and another to confirm that backups were made — possibly by putting the files into a secure dropbox folder, digivin.io db backups, and then a folder for each application backed up?
[10/7/15, 10:49:03 PM] Pamela Snyder: i love the way you think.   i agree completely.   so, Praful, you will make backups in dropbox of KW, ES, Bloom, DD ES, DD KW, DigiVino, GOsustainably, Beach, CASA and Madavier and show them to me a week from today Wed Oct 14.    After that we can do it monthly for certain clients. agreed?

**Comment by PrafulGondekar** [comment]
Agree, I made the db backups in dropbox & share it with you for the applications KW, ES, Bloom, DD & Madavier.

I need the others applications credentials for make a backup for those. i.e. - GOsustainably, Beach &  CASA.
Thanks....!!

**Comment by digipam** [comment]
You are now on those projects, so you have access to the wiki.  thx!

**Comment by PrafulGondekar** [comment]
Done...!!

But on BeachHigh project, i were not able to login, i did use wiki's credential but not working there. May be i used a wrong credentials but even let me know the credentials.

Thanks

**Comment by wizardwerdna** [comment]
To document how to create the backup files in the digivino style, using WP Migrate DB Pro:

## Creating a Backup Profile

* Log into the WP admin
* In the Plugins panel, click on the Settings Button for WP Migrate DB Pro:

![image](https://cloud.githubusercontent.com/assets/3230/10431846/5d9833ea-70bc-11e5-905d-bf8d0414472c.png)

* Go to the migrate tab.

* If there isn't already a Backup profile, click on "Nope, let's start fresh"

![image](https://cloud.githubusercontent.com/assets/3230/10431894/9620bd2c-70bc-11e5-84c0-f31dbc9c6d2f.png)

* Select "Export File", the defaults will be fine.

![image](https://cloud.githubusercontent.com/assets/3230/10431921/cdf8e378-70bc-11e5-8969-ffdc603187a1.png)

* For the backup profile, delete the find replace rows by clicking on the x that appears when you mouse-over the row.

![image](https://cloud.githubusercontent.com/assets/3230/10431947/fe84f05e-70bc-11e5-8bc6-e4f91d42937b.png)

*  Click on "Save Migration Profile" and "Create New Profile".  Name the profile (I suggest "Backup")

![image](https://cloud.githubusercontent.com/assets/3230/10431988/39efa29c-70bd-11e5-89a7-3e5e7b948349.png)

*  Click "Migrate and Save Profile", and the browser should download the DB backup.  The file is now ready to be copied to the target.

* You may need to add *.sql.gz to your .gitignore file

## Using an Existing Backup Profile

Once you have prepared a Backup Profile, you can make another backup, simply by clicking on the Backup tab, and then Clicking "Migrate and Save Profile.

![image](https://cloud.githubusercontent.com/assets/3230/10432110/fe0ae7cc-70bd-11e5-9e19-af75fb3bd90a.png)

**Comment by digipam** [comment]
Did you use this technique for the DB backups? 

https://github.com/DigiVino/HOW-TO-KEEP-SITES-SAFE

**Comment by PrafulGondekar** [comment]
Yes, I did use this technique for the DB backups.
I need credentials for BeachHigh &  DigiVino projects. Provide me the credentials for those projects.

Thanks...!!

**Comment by digipam** [comment]
Great. Thx.

Regarding logins for DV and Beach: You are now on those projects, so you have access to the wiki. thx!

**Comment by PrafulGondekar** [comment]
I have make a DB backups for all application for this week.

**Comment by digipam** [comment]
YOU ROCK!!!!!
